version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    command: ["node", "server.js"]

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "27018:27017"
    restart: always
