version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    command: ["node", "server.js"]


  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    restart: always
