version: '3'
services:
  web:
    image: node:ecomstore
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - "27018:27017"
    restart: always
  redis:
    image: redis:latest
    command: ["redis-server" ,"--port", "6318"]
    ports:
      - "6389:6318"
    restart: always
