version: '3'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - "27018:27017"
    restart: always
  redis:
    image: redis:latest
    command: ["redis-server"]
    ports:
      - "6380:6379"
    restart: always
