version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    # restart: always
    command: ["npm", "run", "start"]


  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - "27018:27017"
    restart: always
