version: '3'
services:
  web:
    build: .
    image: storeAPI
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    ports:
      - "27018:27017"
    restart: always
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    restart: always
